---

- hosts: webservers
  remote_user: "{{ appuser }}"
  roles:
    - role: common
    - role: EDITD.supervisormain
    - role: ssl
    - role: jdauphant.nginx
      sudo: yes
      nginx_http_params:
          # sendfile causes problems with virtualbox
          - sendfile {{ 'off' if vagrant else 'on' }}
      nginx_sites:
        default:
          - listen {{ http_port if http_port != 443 else '443 ssl' }}
          - ssl_certificate_key /etc/nginx/ssl/ssl.key
          - ssl_certificate /etc/nginx/ssl/ssl-unified.crt
          - root {{ assetdir }}
          - location = /peerjs {
                proxy_pass http://tornado;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
          - location = /peerjs/id {
                proxy_pass http://tornado;
            }
          # Turn off caching for everything.  #TODO cache busting
          - expires off
      nginx_configs:
        upstream:
            - upstream tornado { server 127.0.0.1:{{ tornado_port }}; }
        map:
            - map $http_upgrade $connection_upgrade {
                  default upgrade;
                  '' close;
              }
